### ISSUE TITLE
擦除时颜色是黑色

### ISSUE THREAD

**Issue by longch** [fluttercandies/flutter_drawing_board#11]
https://user-images.githubusercontent.com/2062905/159172659-67828ac0-a83e-440d-b2ab-dde37c957ae4.mp4

Version information

Device: iPhone iPhone6s plus
OS: iOS 14.7.1
Package Version: 0.2.7
Flutter Version:2.10.1

**Comment by xSILENCEx** [comment]
这是故意设计成这个样子的。首先为了性能考虑，擦除动作并不会实时生效，抬起后才会触发真正的擦除；其次为了更清楚地预览擦除路径和范围，所以才预设了一个黑色
