### ISSUE TITLE
已经存在的画布无法用橡皮擦擦除

### ISSUE THREAD

**Issue by seth-shi** [fluttercandies/flutter_drawing_board#15]
当 body 是一个已经绘制好的图像, 橡皮擦不能擦除 (是否可以设置成覆盖白色上去就行.)

**Comment by xSILENCEx** [comment]
background与画板不在同一层，所以无法擦除只能覆盖，建议通过[自定义绘制](https://github.com/fluttercandies/flutter_drawing_board#%E8%87%AA%E5%AE%9A%E4%B9%89%E7%BB%98%E5%88%B6)创建特殊橡皮，绘制颜色设置为背景色，可以模拟擦除图片效果

**Comment by seth-shi** [comment]
好的,感谢. 我这边直接用画笔设置为背景色覆盖上去处理了
