### ISSUE TITLE
Online Streaming

### ISSUE THREAD

**Issue by Alijaaan** [fluttercandies/flutter_drawing_board#16]
Is there any way to use this package for online whiteboard?

**Comment by Chappie74** [comment]
Of course.  You'd have to set up a socket server and pass the drawing data between the clients.

The `DrawingBoard` widget contains parameters for you to listen/react to the changes on the drawing board. There are 3 of them: `onPanStart`, `onPanUpdate` and `onPanEnd`. 

The  controller for that widget, `DrawingController` contains methods that allow you to programmatically draw on the canvas, namely, `controller.drawing`, `controller.startDraw` and `controller.endDraw`. The first two takes an `offset` parameter.

You can then have a socket server which from one client emits offset from `onPanStart`, `onPanUpdate` and `onPanEnd`
and for each event call the respective function on the receiving client with the offset parameter passed to programmatically draw on the canvas.

**Comment by Alijaaan** [comment]
Many thanks for your great answer.
I did it but still have one problem,
I have no problem with SimpleLine and it works fine.
But in other types like circle or rectangle I cant handle it.

**Comment by Alijaaan** [comment]
I found that I should do something like this on destination:
_drawingController?.setPaintContent = Rectangle();
Many thanks for your kind help :)

**Comment by Chappie74** [comment]
If you would like, we can discuss on discord.

 Chappie74#9006
