### ISSUE TITLE
Support insert text ?

### ISSUE THREAD

**Issue by vankhai1997** [fluttercandies/flutter_drawing_board#21]

**Comment by xSILENCEx** [comment]
View this package: [stack_board](https://pub.flutter-io.cn/packages/stack_board)
`stack_board` is being refactored and a new version with a lot of new changes will be released soon

**Comment by Doczure-75** [comment]
Any progress here?

**Comment by xSILENCEx** [comment]
[stack_board](https://pub.flutter-io.cn/packages/stack_board)
