### ISSUE TITLE
请教一下如何设置才能把画板弄成全屏而不是居中呢？

### ISSUE THREAD

**Issue by alonsolee** [fluttercandies/flutter_drawing_board#22]

**Comment by xSILENCEx** [comment]
之前的布局限制比较多，已发布0.4.3增加了布局的可扩展性，Example: https://painter.liugl.cn/

**Comment by alonsolee** [comment]
感谢老铁回复。
再问一下，因为我用的flutter版本是2.10.5.现在直接引用git的依赖是0.41+5.请问要怎么写才能引用到0.4.3？

**Comment by xSILENCEx** [comment]
flutter_drawing_board: ^0.4.3+1
