### ISSUE TITLE
support canRedo / canUndo / canClear

### ISSUE THREAD

**Issue by huntrist** [fluttercandies/flutter_drawing_board#29]
please consider support
controller.canRedo()
controller.canUndo()
controller.canClear()

so we can set the UI icons inactive/active based on state. Thanks~

**Comment by Chappie74** [comment]
What you can also do is not render the icons that come default and create your own icons.

**Comment by ologunB** [comment]
check my implementation. it handles canRedo, canUndo and canClear

import 'package:flutter_drawing_board/flutter_drawing_board.dart';
import 'package:flutter_drawing_board/paint_contents.dart';

import 'rev_text.dart';

class RevDrawSignature extends StatefulWidget {
  const RevDrawSignature({super.key});

  @override
  State<RevDrawSignature> createState() => _RevDrawSignatureState();
}

class _RevDrawSignatureState extends State<RevDrawSignature> {
  DrawingController _drawingController = DrawingController();

  @override
  void initState() {
    _drawingController = DrawingController(
        // content: PaintContent
        );
    super.initState();
  }

  List<PaintContent> history = [];

  @override
  Widget build(BuildContext context) {
    return ListView(
      shrinkWrap: true,
      children: [
        const Align(alignment: Alignment.topRight, child: CloseButton()),
        RevText(
          'Sign below to acknowledge the loan',
          fontSize: 16.sp,
          align: TextAlign.center,
          color: Colors.black,
          top: 5.h,
          bottom: 20.h,
          fontWeight: FontWeight.w500,
        ),
        SizedBox(
          height: MediaQuery.of(context).size.width,
          child: DrawingBoard(
            boardPanEnabled: false,
            boardScaleEnabled: false,
            controller: _drawingController,
            onPointerMove: (a) {
              setState(() {});
            },
            onPointerDown: (a) {
              setState(() {});
            },
            onPointerUp: (a) {
              setState(() {});
            },
            background: Container(
              width: MediaQuery.of(context).size.width,
              height: MediaQuery.of(context).size.width,
              color: Colors.black12,
            ),
          ),
        ),
        Padding(
          padding: EdgeInsets.symmetric(horizontal: 24.h, vertical: 10.h),
          child: Row(
            children: [
              Expanded(
                child: RevButton(
                  'Undo',
                  buttonColor: AppColors.green,
                  height: 40,
                  fontSize: 14.sp,
                  fontWeight: FontWeight.w400,
                  textColor: Colors.white,
                  borderColor: AppColors.green,
                  borderRadius: 100.h,
                  onPressed: _drawingController.getHistory.isEmpty
                      ? null
                      : () {
                          if (_drawingController.currentIndex == 1) {
                            history = [];
                            history.addAll(_drawingController.getHistory);
                            _drawingController.clear();
                          }

                          _drawingController.undo();
                          setState(() {});
                        },
                ),
              ),
              SizedBox(width: 12.h),
              Expanded(
                child: RevButton(
                  'Redo',
                  buttonColor: AppColors.green,
                  height: 40,
                  fontSize: 14.sp,
                  fontWeight: FontWeight.w400,
                  textColor: Colors.white,
                  borderColor: AppColors.green,
                  borderRadius: 100.h,
                  onPressed:
                      _drawingController.getHistory.isEmpty && history.isEmpty
                          ? null
                          : () {
                              if (_drawingController.currentIndex == 0 &&
                                  history.isNotEmpty) {
                                _drawingController.addContents(history);
                              }
                              _drawingController.redo();
                              setState(() {});
                            },
                ),
              ),
              SizedBox(width: 12.h),
              Expanded(
                child: RevButton(
                  'Clear',
                  buttonColor: AppColors.green,
                  height: 40,
                  fontSize: 14.sp,
                  fontWeight: FontWeight.w400,
                  textColor: Colors.white,
                  borderColor: AppColors.green,
                  borderRadius: 100.h,
                  onPressed: _drawingController.currentIndex == 0 &&
                          _drawingController.getHistory.isEmpty
                      ? null
                      : () {
                          history = [];
                          history.addAll(_drawingController.getHistory);
                          _drawingController.clear();
                          setState(() {});
                        },
                ),
              ),
            ],
          ),
        ),
        Padding(
          padding: EdgeInsets.all(24.h),
          child: RevButton(
            'Confirm Signature',
            buttonColor: AppColors.green,
            height: 66,
            fontSize: 16.sp,
            fontWeight: FontWeight.w400,
            textColor: Colors.white,
            borderColor: AppColors.green,
            borderRadius: 100.h,
            onPressed: _drawingController.getHistory.isEmpty
                ? null
                : () async {
                    Uint8List? bytes = (await _drawingController.getImageData())
                        ?.buffer
                        .asUint8List();

                    Navigator.pop(context, bytes);
                  },
          ),
        ),
      ],
    );
  }
}

**Comment by xSILENCEx** [comment]
Merged in 0.6.0

**Comment by aktasilyas** [comment]
when you try to erase it with an eraser, it also erases the picture, how can we prevent this?
