### ISSUE TITLE
Select & edit shape support

### ISSUE THREAD

**Issue by hupo376787** [fluttercandies/flutter_drawing_board#31]
Like rectangles, circles, ellipses, polygons, etc.

Like a circle, when selected, show the center and four points(top, bottom, left, right). Select the center point to move the shape, and select top or other to change the radius.

**Comment by mag1c-dev** [comment]
Hello, I would like to introduce to you a package that can help you do this. 
Here is the pub.dev link: https://pub.dev/packages/magic_canvas

**Comment by hupo376787** [comment]
> Hello, I would like to introduce to you a package that can help you do this. Here is the pub.dev link: https://pub.dev/packages/magic_canvas

Wow, great work, thx.

**Comment by xSILENCEx** [comment]
Sorry, this package will only contain the most basic drawing functions
