### ISSUE TITLE
One-finger smudge and two-finger zoom work fine, but more than three fingers cause the smudge gesture to fail[Discussions] 

### ISSUE THREAD

**Issue by freedom6xiaobai** [fluttercandies/flutter_drawing_board#32]
### Content

One-finger smudge and two-finger zoom work fine, but more than three fingers cause the smudge gesture to fail

<img width="660" alt="image" src="https://github.com/fluttercandies/flutter_drawing_board/assets/13901443/4b5c1115-9c3b-4ad5-a3ce-1f77f6df8441">

<img width="521" alt="image" src="https://github.com/fluttercandies/flutter_drawing_board/assets/13901443/cdda1bd3-a8fa-48a4-941b-59de073b46a3">

It is recommended that Listener listens to add onPointerCancel callback

**Comment by xSILENCEx** [comment]
Fixed in 0.6.0
