### ISSUE TITLE
[How to use] How to get view drawn call back like view drawing started completed etc

### ISSUE THREAD

**Issue by Jamalzahid** [fluttercandies/flutter_drawing_board#33]
### Platforms

dart

### Description

How to get view drawn call back like when user start drawing smooth line when user puts finger and start moving in some area to draw line call back should be return when drawing started and completed a view  view drawing started completed etc

**Comment by xSILENCEx** [comment]
```dart
const DrawingBoard({
    ...
    this.onPointerDown,
    this.onPointerMove,
    this.onPointerUp,
    ...
  });
```

These three callbacks can detect finger status

**Comment by Jamalzahid** [comment]
Thank you so much
