### ISSUE TITLE
[Bug report] 

### ISSUE THREAD

**Issue by saddamAfzal07** [fluttercandies/flutter_drawing_board#38]
### Version

0.5.0

### Platforms

dart, Android, iOS

### Device Model

Android 11

### flutter info

```sh
I used this package and modify it,s functionality according to my requirnments but one thing i am not able to modify is the moveable canvas. Canvas should be fixed at it,s position while drawing or writing anything onit kindly do these changes in the latest version
```

### How to reproduce?

I used this package and modify it,s functionality according to my requirnments but one thing i am not able to modify is the moveable canvas. Canvas should be fixed at it,s position while drawing or writing anything onit kindly do these changes in the latest version

### Logs

```sh
I used this package and modify it,s functionality according to my requirnments but one thing i am not able to modify is the moveable canvas. Canvas should be fixed at it,s position while drawing or writing anything onit kindly do these changes in the latest version
```

### Example code (optional)

```Dart
I used this package and modify it,s functionality according to my requirnments but one thing i am not able to modify is the moveable canvas. Canvas should be fixed at it,s position while drawing or writing anything onit kindly do these changes in the latest version
```

### Contact

saddamafzal07gmail.com

**Comment by xSILENCEx** [comment]
I can't reproduce the problem. Can you provide a minimal reproduction demo?

**Comment by xSILENCEx** [comment]
Duplicate with #34
