### ISSUE TITLE
[Feature request] Fix the canvas

### ISSUE THREAD

**Issue by AliYar-Khan** [fluttercandies/flutter_drawing_board#39]
### Platforms

Android, iOS, macOS, Web, Windows, Linux

### Description

I am trying to make the canvas fixed but there is no option currently available. 

### Why

I am trying to make the canvas fixed but there is no option currently available.

**Comment by AliYar-Khan** [comment]
https://github.com/fluttercandies/flutter_drawing_board/assets/37889962/b3a19503-9719-4103-8bf5-73129ef21416

As you can see here the canvas is moving. I want to fix its position!

**Comment by xSILENCEx** [comment]
Use `boardPanEnabled: false` to disable dragging
Use `boardScaleEnabled: false` to disable scaling

```dart
DrawingBoard(
  boardPanEnabled: false,
)
```
If you still have problems, please open this issues again

**Comment by xSILENCEx** [comment]
Duplicate with #34
