### ISSUE TITLE
[Feature request] load from json

### ISSUE THREAD

**Issue by KevDev99** [fluttercandies/flutter_drawing_board#46]
### Platforms

dart

### Description

as there is a `getJsonList` function on the `DrawingController` it would be also good to reuse that json data to overhand as initial json payload. there is now no way to do that

### Why

allows to save a snapshot of the drawing and reuse later

**Comment by xSILENCEx** [comment]
```dart
const Map<String, dynamic> _testLine1 = <String, dynamic>{
  'type': 'StraightLine',
  'startPoint': <String, dynamic>{'dx': 68.94337550070736, 'dy': 62.05980083656557},
  'endPoint': <String, dynamic>{'dx': 277.1373386828114, 'dy': 277.32029957032194},
  'paint': <String, dynamic>{
    'blendMode': 3,
    'color': 4294198070,
    'filterQuality': 3,
    'invertColors': false,
    'isAntiAlias': false,
    'strokeCap': 1,
    'strokeJoin': 1,
    'strokeWidth': 4.0,
    'style': 1
  }
};

const Map<String, dynamic> _testLine2 = <String, dynamic>{
  'type': 'StraightLine',
  'startPoint': <String, dynamic>{'dx': 106.35164817830423, 'dy': 255.9575653134524},
  'endPoint': <String, dynamic>{'dx': 292.76034659254094, 'dy': 92.125586665872},
  'paint': <String, dynamic>{
    'blendMode': 3,
    'color': 4294198070,
    'filterQuality': 3,
    'invertColors': false,
    'isAntiAlias': false,
    'strokeCap': 1,
    'strokeJoin': 1,
    'strokeWidth': 4.0,
    'style': 1
  }
};

  ...

/// Add Json test content
void _addTestLine() {
  _drawingController.addContent(StraightLine.fromJson(_testLine1));
  _drawingController.addContents(<PaintContent>[StraightLine.fromJson(_testLine2)]);
}
```

**Comment by xSILENCEx** [comment]
Is this what you need?

**Comment by KevDev99** [comment]
no, that was already what i saw from the docs. What i actually mean is that there is a function to get the current state as json:
```
/// Get Json content
Future<void> _getJsonList() async {
  print(const JsonEncoder.withIndent('  ').convert(_drawingController.getJsonList()));
}
```

But no function to initially load the drawing board with that exported json content.

This would be a huge improvement to save the current state to a db and reload it when opening again the drawing board.

**Comment by xSILENCEx** [comment]
This is not feasible. The controller needs PaintContent, and json needs to be converted to PaintContent first.

**Comment by JulienElkaim** [comment]
This feature would be a must-to-have to make the package easy to use !

### Context I understand
@xSILENCEx looking at your implementation of `PaintContent#toJson`,  it seems you first wanted to support it right? 
You force the JSON representation returned by `DrawingController#getJsonList` to have a "type" field.

Unfortunately, it looks like the Web version is terrible at this as it modifies the class name... runtimeType can't be used:
<img width="324" alt="Screenshot 2024-09-24 at 8 11 37 PM" src="https://github.com/user-attachments/assets/7e3aae9f-0c0d-440a-af9d-5617e1a65bef">
https://xsilencex.github.io/flutter_drawing_board_demo/ 

### Suggestion of Impl

As the current impl for "type" does not work (not consistent value in web version), could we modify the behaviour?


1) Add a `toJsonKey` method in `PaintContent` class. By default not implemented:
```dart
/**
   * Key used to identify the PaintContent object as JSON.
   * is used for the "type" field in the JSON object created by PaintContent#toJson.
   * 
   * Meant to be used by DrawingController#loadFromJson method to deserialize.
   */
  String toJsonKey(){
    throw UnimplementedError("To Jsonify this object, please implement this method");
  }
```


2) For default `PaintContent` provided (`Smoothline`, `SimpleLine`, `Rectangle`, etc...), hardcode a UUID value or whatever. i.e:
```dart
class SimpleLine extends PaintContent {
  static const jsonTypeKey = "ED4D3A1A-3A3A-4D3A-8D3A-3A3A4D3A3A4D3";
  @override
  String toJsonKey(){
    return SimpleLine.jsonTypeKey;
  }
//...
```


3) The user will implement its own `toJsonKey` for custom `PaintContent`. User is responsible to provide uniq values :
```dart
class MyAwesomeTriangle extends PaintContent {
  static const jsonTypeKey = "AB493-3A3A-AAAA-985-DDDD1637";
  @override
  String toJsonKey(){
    return MyAwesomeTriangle.jsonTypeKey;
  }
//...
```


4) `DrawingConfig` OR `DrawingController` (as you prefer, maybe controller?) has a new field called  `deserializationMap`. By Default, the package fill-in the ones for the native PaintContent:
```dart
final Map<String, PaintContent Function(Map<String, dynamic>)> deserializationMap = {
    SimpleLine.jsonTypeKey: (data) => SimpleLine.fromJson(data),
    SmoothLine.jsonTypeKey: (data) => SmoothLine.fromJson(data),
    Rectangle.jsonTypeKey: (data) => Rectangle.fromJson(data),
    Circle.jsonTypeKey: (data) => Circle.fromJson(data),
    Eraser.jsonTypeKey: (data) => Eraser.fromJson(data),
  };
```

5) The user can provide it's map for the deserialization of custom PaintContent. At constructor or in a setter. Native deserializers can be override in the process  : 
```dart
void updateDeserializationMap(Map<String, PaintContent Function(Map<String, dynamic>)> customMap){
    var newMap = HashMap<String, PaintContent Function(Map<String, dynamic>)>();
    newMap = newMap..addAll(deserializationMap)..addAll(customMap);
  }
 ```


6) the Controller can now use this map to perform a `addContentsFromJson(String jsonListAsString)` or something similar:
```dart
  void addContentsFromJson(String jsonListAsString){
    List<Map<String, dynamic>> listOfJson = jsonDecode(jsonListAsString);
    List<PaintContent> contents = listOfJson.map((json) {
      String type = json['type'];
      return deserializationMap[type]!(json);
    }).toList();
    
    _drawingController.addContents(contents);
  }
```


7) If we care about retro compatibility for users on **non-WEB platforms** relying on the type field, we can add to the default deserializationMap the predictible runtimeType:
```dart
final Map<String, PaintContent Function(Map<String, dynamic>)> deserializationMap = {
    SimpleLine.jsonTypeKey: (data) => SimpleLine.fromJson(data),
    SmoothLine.jsonTypeKey: (data) => SmoothLine.fromJson(data),
   //...
    'SimpleLine': (data) => SimpleLine.fromJson(data),
    'SmoothLine': (data) => SmoothLine.fromJson(data),
    'Rectangle': (data) => Rectangle.fromJson(data),
    //...
  };
```
