### ISSUE TITLE
[Feature request] Erase PaintContent on tap

### ISSUE THREAD

**Issue by dinomel** [fluttercandies/flutter_drawing_board#49]
### Platforms

Android, iOS

### Description

I need a way to delete (erase) previously added content by tapping on it on the canvas. The undo button erases the last added content, but i need to erase any content at any time.

### Why

The eraser can only "paint" the color of the background so it seems like the user is erasing parts of a PaintContent. If a user wants to erase the whole PaintContent it would be very hard to do so with this kind of eraser.

**Comment by xSILENCEx** [comment]
Fixed in [0.8.1 ](https://pub.dev/packages/flutter_drawing_board)
