### ISSUE TITLE
Delay in drawing on the big screen

### ISSUE THREAD

**Issue by SerdarYildiz06** [fluttercandies/flutter_drawing_board#52]
### Content

Problem: A slight delay in the drawings
Platfrom: Linux
Device Screen: Smart Board
Flutter sdk version: 3.19.6
Drawing board version: 0.8.1

https://github.com/user-attachments/assets/bd934838-16a2-41d0-978e-49e0fecce8cc

**Comment by SerdarYildiz06** [comment]
@xSILENCEx sir do you have any suggection on this case?

**Comment by xSILENCEx** [comment]
If you still have problems, please open it again
