### ISSUE TITLE
[Bug report] 

### ISSUE THREAD

**Issue by llqidian** [fluttercandies/flutter_drawing_board#53]
### Version

0.9.2

### Platforms

dart

### Device Model

android

### flutter info

```sh
Flutter version 3.22.2
```

### How to reproduce?

我在widget上画完后 我轻点画板 就会显示成锯齿状
<img width="923" alt="截屏2024-08-29 11 32 48" src="https://github.com/user-attachments/assets/66a670d0-1da5-4d17-ab7a-1270a8ddc629">

**Comment by llqidian** [comment]
而且我在画板边缘操作的时候还能拖动画板位置

**Comment by xSILENCEx** [comment]
Fixed in [0.9.3](https://pub.dev/packages/flutter_drawing_board)
