### ISSUE TITLE
[Discussions] v0.8.1 managed to inherit height and width from Parent widgets which doesn't work after v0.9.1

### ISSUE THREAD

**Issue by PratikSingh121** [fluttercandies/flutter_drawing_board#54]
### Issue: Loss of Inherited Height and Width in `flutter_drawing_board` after v0.9.1

**Affected Version:** v0.9.1 and later  
**Previous Working Version:** v0.8.1  

#### Description:
In version v0.8.1 of the `flutter_drawing_board` package, the `DrawingBoard` widget used to inherit its `height` and `width` from the parent widget automatically. This made it convenient to set up dynamic layouts, such as embedding the drawing board in a `Stack` or other scrollable containers, where the board's size would adjust based on the parent constraints.

However, starting from version v0.9.1, the `background` attribute's container no longer inherits the height and width from its parent. Instead, the constraints remain `(0,0)`, causing issues when trying to dynamically size the `DrawingBoard`. As a result, it's now difficult to produce a drawing board with a dynamic size based on layouts like `Stack` or `SingleChildScrollView`.

#### Example:
This code used to work in v0.8.1 but no longer functions correctly in v0.9.1:

```dart
SingleChildScrollView(
  child: Stack(
    children: <Widget>[
      const pdfOutput(),  // Example of dynamic content
      Positioned.fill(
        child: DrawingBoard(
          controller: controller,
          background: Container(),   // This used to inherit size from parent
          showDefaultActions: true,
          showDefaultTools: true,
        ),
      ),
    ],
  ),
)
```

In this case, the `Container` inside the `background` attribute should inherit the size of the `Stack`, but with `v0.9.1+`, it remains with a size of `(0,0)`.

### Expected Behavior (v0.8.1):
The `DrawingBoard` should inherit the size from its parent widget, allowing it to dynamically resize based on the layout constraints.

### Actual Behavior (v0.9.1+):
The size of the `DrawingBoard` remains `(0,0)`, making it impossible to set dynamic sizes based on parent constraints.

Please advise if there are any recommended fixes or workarounds, or if this behavior change is intended.

**Comment by xSILENCEx** [comment]
You can nest `LayoutBuilder` after `Positioned.fill` to solve this problem:

```dart
Positioned.fill(
  child: LayoutBuilder(
    builder: (BuildContext context, BoxConstraints constraints) {
      return DrawingBoard(
        background: Container(
          width: constraints.maxWidth,
          height: constraints.maxHeight,
        ),
      );
    },
  ),
),
```
