### ISSUE TITLE
[Bug report] Incorrect 'type' value ("minified  ") in DrawingController.getJsonList on Web Release Version

### ISSUE THREAD

**Issue by youshail** [fluttercandies/flutter_drawing_board#58]
### Version

last

### Platforms

dart

### Device Model

Web (Release)

### flutter info

```sh
Flutter: ">=3.3.2 <4.0.0"
```

### How to reproduce?

Hello,
I am using the flutter_drawing_board package in my web application and have encountered an issue with the DrawingController.getJsonList method. Specifically, the "type" field is returning an incorrect value in the web release version.
Here are the details:
* Environment:
    * Flutter: ">=3.3.2 <4.0.0"
    * Platform: Web (Release)
* Problem: When calling DrawingController.getJsonList, the "type" key in the returned JSON shows an unexpected value like "minified:uo", instead of the expected type (such as "SimpleLine", "Circle", etc.). This issue only occurs in the web release version, and everything works fine in the debug mode.
* Steps to reproduce:
    1. Visit your online demo and draw shapes using the DrawingController.
    2. Call getJsonList and inspect the "type" value in the JSON returned.
    3. You will observe that the "type" field returns an unexpected value like "minified:uo", rather than the correct type.
* Screenshots: I am attaching screenshots from your demo to illustrate the issue: 
<img width="1360" alt="Capture d’écran 2024-09-24 à 09 29 15" src="https://github.com/user-attachments/assets/f1a13b97-3e6c-4702-8acb-da4055d2bd2b">

* Expected behavior: The "type" field in the JSON returned by getJsonList should provide the correct value corresponding to the drawn shape, such as "SimpleLine", "Circle", etc.
Thank you for your help, and I look forward to your assistance in resolving this issue!

**Comment by xSILENCEx** [comment]
I've added a getter for “contentType” and overridden the internal drawing object so that we can override this getter without affecting other developers.

```dart
abstract class PaintContent {
  ...
  /// contentType for web
  String get contentType => runtimeType.toString();
  ...
}
```
